mybatis-plus:
  mapper-locations: classpath:mybatisplus/mapper/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.cilicili.Beans
spring.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/cilicili?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: root
  password: root
  druid:
    test-while-idle: true
    validation-query: SELECT 1
spring:
  redis:
    host: localhost
    port: 6379
    connect-timeout: 5000
  sql:
    init:
      platform: mysql
server:
  ssl:
    key-store: classpath:cert.p12 # 证书存放的位置
    key-store-type: PKCS12 # P12证书格式
    key-store-password:
    enabled: true
logging:
  level:
    com.cilicili.DAO.Mapper: debug
