mybatis-plus:
  mapper-locations: classpath:mybatisplus/mapper/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.cilicili.Beans
spring.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/cilicili?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: root
  password: root
  druid:
    test-while-idle: true
    validation-query: SELECT 1
spring:
  redis:
    host: localhost
    port: 6379
    connect-timeout: 5000
  sql:
    init:
      platform: mysql
